#!/usr/bin/env bash
# Set AI-BOM up to run on boot.
#   scripts/install-service.sh            # pm2 (cross-platform)
#   scripts/install-service.sh --systemd  # systemd unit (Linux servers)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MANAGER="pm2"
for arg in "$@"; do
  case "$arg" in
    --systemd) MANAGER="systemd" ;;
    --pm2) MANAGER="pm2" ;;
    -h|--help) sed -n '2,4p' "$0"; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

if [ ! -f .aibom-mode ]; then
  echo "Run scripts/setup.sh first." >&2
  exit 1
fi
# shellcheck disable=SC1091
. .aibom-mode

if [ "$MODE" = "docker" ]; then
  cat <<'EOF'
Docker mode already restarts on boot:
  - docker-compose.yml uses `restart: unless-stopped`
  - set Docker Desktop to start on login (Settings -> General), or on Linux:
      sudo systemctl enable docker
Then `scripts/start.sh` once, and the stack comes back after every reboot.
EOF
  exit 0
fi

if [ "$MANAGER" = "pm2" ] && ! command -v pm2 >/dev/null 2>&1; then
  echo "pm2 not found — install it first: npm install -g pm2" >&2
  exit 1
fi

echo "Building the production bundle…"
(cd packages/shared && npm install && npm run build)
(cd backend && npm install && npm run prisma:generate && npm run build)
(cd frontend && npm install && npm run build)

if [ "$MANAGER" = "pm2" ]; then
  cat > ecosystem.config.cjs <<EOF
// Generated by scripts/install-service.sh
module.exports = {
  apps: [
    {
      name: "aibom",
      script: "scripts/serve-prod.sh",
      interpreter: "bash",
      cwd: "$ROOT_DIR",
      autorestart: true,
      max_restarts: 10,
    },
  ],
};
EOF
  echo "Wrote ecosystem.config.cjs. Now run:"
  echo "  pm2 start ecosystem.config.cjs && pm2 save && pm2 startup"
  exit 0
fi

# systemd
UNIT=/etc/systemd/system/aibom.service
SERVICE_USER="${SUDO_USER:-$(id -un 2>/dev/null || echo aibom)}"
cat <<EOF
Install this unit as root (${UNIT}):

[Unit]
Description=AI Asset Governance Tool
After=network.target docker.service

[Service]
Type=exec
User=${SERVICE_USER}
WorkingDirectory=${ROOT_DIR}
ExecStart=${ROOT_DIR}/scripts/serve-prod.sh
ExecStopPost=/usr/bin/env bash -c 'cd ${ROOT_DIR}/backend && npm run --silent db:stop || true'
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

Then:
  sudo systemctl daemon-reload
  sudo systemctl enable --now aibom.service
  sudo systemctl status aibom.service
EOF
